#!/bin/sh

set -e

clear

system_type=
scriptfile=

if [ -f "/etc/void-release" ]; then
    system_type="void"
elif [ -f "/etc/artix-release" ]; then
    system_type="artix"
fi

case "$system_type" in
    "void")
        scriptfile="$HOME/.config/yadm/deps-void.sh"
        ;;
    "artix")
        scriptfile="$HOME/.config/yadm/deps-artix.sh"
        ;;
    *)
        ;;
esac

if [ -z "$scriptfile" ]; then
    echo "Cannot find install script for ${system_type}Linux. Exiting."
    exit 1
fi

echo "Installing for ${system_type}Linux."
echo -n "Do you want to proceed? "
read reply
case "$reply" in
    y|yes|Y|YES)
        ;;
    *)
        echo "Installation cancelled."
        exit 1
        ;;
esac

. $scriptfile
