#!/bin/sh

# default arch init scripts
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
fi

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

# Activate dbus variables
if [ -z "${XDG_RUNTIME_DIR:-}" ] || [ ! -d "${XDG_RUNTIME_DIR}" ]; then
    uid="$(id -u)"
    export XDG_RUNTIME_DIR="/tmp/runtime-$uid"
    install -d -m 700 "$XDG_RUNTIME_DIR"
fi
dbus-update-activation-environment --all
dbus-launch ssh-agent i3
