#!/bin/sh

autostart="mpd mpDris2 transmission-daemon unclutter pipewire xfsettingsd"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# NOTE: Colors are derived from Xresources, so make sure
# they are sourced out first before calling the rest of
# scripts below
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/xresources" ]; then
	xrdb -merge "${XDG_CONFIG_HOME:-$HOME/.config}/shell/xresources"
else
	xrdb -merge "$HOME/.Xresources"
fi

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"

. "$HOME/.local/bin/setcolors" &
