#!/bin/sh

LOC=$LOCATION_RS
CTEMP=5500:4500
AUTOLOCK_TIMEOUT=10 # timeout in minutes
LOCKSCREEN_CMD="betterlockscreen -l"

run() {
    if command -v $1 >/dev/null; then
	    if ! pgrep -x $1 >/dev/null; then
			echo "$@"
		    $@&
	    fi
    fi
}

xset s off
xset -dpms 

# load Xresources
if [ -f "$HOME/.Xresources" ]; then
	xrdb -merge "$HOME/.Xresources"
else
	xrdb -merge "${XDG_CONFIG_HOME:-$HOME/.config}/shell/xresources"
fi

run "xfsettingsd"

nitrogen --restore & # restore background wallpaper
# . "$HOME/.local/bin/load_icm_profile" &   # load monitor profile
xsetroot -cursor_name left_ptr &     # general system settings
numlockx &
# daemons
run /usr/libexec/polkit-gnome-authentication-agent-1
run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg) &

run "mpd"                                   # music player widget
run "sxhkd"                                 # X hotkey daemon
run "redshift" " -t $CTEMP -l $LOC"

# tray icons
run "connman-gtk" "--tray"                # network manager gtk ui
run "volumeicon"                          # volume icon
run "nm-applet"                           # networkmanager
run "blueman-applet"                      # bluetooth

if command -v transmission-daemon >/dev/null; then
	if ! pgrep -x transmission-da >/dev/null; then
		transmission-daemon &
	fi
fi

sleep 0.5

. "$HOME/.local/bin/launch_picom" &         # kills and relaunch compositor
. "$HOME/.local/bin/launch_polybar" &       # kills and relaunch panel
. "$HOME/.local/bin/launch_dunst" &         # kills and relaunch notification daemon
. "$HOME/.local/bin/setcolors" &			# exports color configs to rofi, kitty ...
# . "$HOME/.local/bin/autolock" 5 &

ksuperkey -e 'Super_L=Alt_L|F1'
