#!/bin/bash

_c() { bspc config "$@"; }
_m() { bspc monitor "$@"; }
_r() { bspc rule "$@"; }

export PATH=${PATH}:${HOME}/.local/bin:${HOME}/.local/bin/transmission

## autostart programs
. "$HOME/.config/bspwm/autostart"
## get colors from xrdb
. "$HOME/.local/bin/getcolors"

# set theme
_c normal_border_color          "$BACKGROUND" #
_c active_border_color          "$MAGENTA" #
_c focused_border_color         "$RED" #
_c presel_feedback_color        "$GREEN" # apply colors to windows

## monitor settings
_m -d                           1 2 3 4 5 6 7 8 9

## application rules
bspc config external_rules_command ~/.config/bspwm/external_rules

## window settings
_c border_width                 1
_c window_gap                   5
_c top_padding                  24
_c bottom_padding               0
_c split_ratio                  0.52

_c single_monocle               true
_c borderless_monocle           true
_c gapless_monocle              true

## mouse behaviors
_c focus_follows_pointer        true
