#!/bin/bash

## autostart programs
. $HOME/.local/bin/bspwm/startup &

_c() { bspc config "$@"; }
_m() { bspc monitor "$@"; }
_r() { bspc rule "$@"; }

## add some colors to bspwm
_c normal_border_color          "#44475a"
_c active_border_color          "#6272A4"
_c focused_border_color         "#ff79c6"
_c presel_feedback_color        "#6272a4"

## monitor settings
_m -d                           1 2 3 4 5 6 7 8 9

## window settings
_c border_width                 2
_c window_gap                   10
_c top_padding                  20
_c bottom_padding               0
_c split_ratio                  0.52
_c borderless_monocle           false
_c gapless_monocle              true

## mouse behaviors
_c focus_follows_pointer        true

## application rules

# prevent doubling rules
_r -r "*"

# apply special rules first
_r -a mplayer2                  state=floating
_r -a Kupfer.py                 focus=on
_r -a Screenkey                 manage=off
_r -a Lxappearance              state=floating
_r -a Nitrogen                  state=floating
_r -a Nm-connection-editor      state=floating
_r -a Gnome-calculator          state=floating
_r -a *:show_help               state=floating
_r -a *:floating                state=floating
_r -a File-roller               state=floating
_r -a Yad                       state=floating
_r -a nmtui                     state=floating
_r -a retroarch                 state=floating
_r -a yad-calendar              state=floating

_r -a Brave-browser             desktop='^2'    follow=on
_r -a Firefox                   desktop='^2'    follow=on
_r -a "Code - OSS"              desktop='^3'    follow=on
_r -a vscodium                  desktop='^3'    follow=on
_r -a discord                   desktop='^6'    follow=on
