#!/bin/bash

# Opens a terminal to update pacman packages and handle updating polybar
$TERMINAL -e bash -c 'sudo pacman -Syu; read -p "Press any key to close window..."' && polybar-msg -p "$(pidof "polybar")" hook pacman-packages 1 #&& pkill -SIGRTMIN+3 i3blocks

